import bcrypt from 'bcryptjs';
const data = {
  users: [
    {
      name: 'Hisham',
      email: 'hisham4a4d4m@gmail.com',
      password: bcrypt.hashSync('76895508*'),
      isAdmin: true,
    },
    {
      name: 'Mohamed',
      email: 'mohamed4a4d4m@gmail.com',
      password: bcrypt.hashSync('12345678*'),
      isAdmin: false,
    },
    {
      name: 'Aya',
      email: 'aya4a4d4m@gmail.com',
      password: bcrypt.hashSync('76895508'),
      isAdmin: false,
    },
    {
      name: 'Doaa',
      email: 'doaa4a4d4m@gmail.com',
      password: bcrypt.hashSync('76895508'),
      isAdmin: false,
    },
    {
      name: 'Amora',
      email: 'amora4a4d4m@gmail.com',
      password: bcrypt.hashSync('76895508'),
      isAdmin: false,
    },
    {
      name: 'Abdelrahman',
      email: 'abdelrahman4a4d4m@gmail.com',
      password: bcrypt.hashSync('76895508'),
      isAdmin: false,
    },
    {
      name: 'Emad',
      email: 'emad4a4d4m@gmail.com',
      password: bcrypt.hashSync('76895508'),
      isAdmin: false,
    },
  ],
  products: [
    {
      // _id: '1',
      name: 'Nike Slim shirt',
      slug: 'nike-slim-shirt',
      catigory: 'Shirts',
      image: '/images/p1.jpg', //Dimention 679px * 829px
      price: 120,
      countInStock: 3,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      discreption: 'high quality product',
    },
    {
      // _id: '2',
      name: 'Adidas Fit shirt',
      slug: 'adidas-fit-shirt',
      catigory: 'Shirts',
      image: '/images/p2.jpg',
      price: 250,
      countInStock: 5,
      brand: 'Aidas',
      rating: 4.0,
      numReviews: 10,
      discreption: 'high quality product',
    },
    {
      // _id: '3',
      name: 'Nike Slim Pant',
      slug: 'nike-slim-pant',
      catigory: 'Pants',
      image: '/images/p3.jpg',
      price: 25,
      countInStock: 7,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 14,
      discreption: 'high quality product',
    },
    {
      // _id: '4',
      name: 'Adidas Slim Pant',
      slug: 'adidas-slim-pant',
      catigory: 'Pants',
      image: '/images/p4.jpg',
      price: 65,
      countInStock: 10,
      brand: 'Adidas',
      rating: 4.5,
      numReviews: 10,
      discreption: 'high quality product',
    },
  ],
};
export default data;
